#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="C:\\Users\\Enrique\\AppData\\Local\\Temp\\OMB.sdf")]
	public partial class OMBContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategorias(Categorias instance);
    partial void UpdateCategorias(Categorias instance);
    partial void DeleteCategorias(Categorias instance);
    #endregion
		
		public OMBContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OMBContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OMBContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OMBContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Categorias> Categorias
		{
			get
			{
				return this.GetTable<Categorias>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Categorias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _CategoriaID;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<System.Guid> _Parent_CategoriaID;
		
		private EntityRef<Categorias> _Parent_Categoria;
		
		private EntitySet<Categorias> _Categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoriaIDChanging(System.Guid value);
    partial void OnCategoriaIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnCantidadChanging(System.Nullable<int> value);
    partial void OnCantidadChanged();
    partial void OnParent_CategoriaIDChanging(System.Nullable<System.Guid> value);
    partial void OnParent_CategoriaIDChanged();
    #endregion
		
		public Categorias()
		{
			this._Parent_Categoria = default(EntityRef<Categorias>);
			this._Categoria = new EntitySet<Categorias>(new Action<Categorias>(this.attach_Categoria), new Action<Categorias>(this.detach_Categoria));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid CategoriaID
		{
			get
			{
				return this._CategoriaID;
			}
			set
			{
				if ((this._CategoriaID != value))
				{
					this.OnCategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._CategoriaID = value;
					this.SendPropertyChanged("CategoriaID");
					this.OnCategoriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(300)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent_CategoriaID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Parent_CategoriaID
		{
			get
			{
				return this._Parent_CategoriaID;
			}
			set
			{
				if ((this._Parent_CategoriaID != value))
				{
					if (this._Parent_Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnParent_CategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._Parent_CategoriaID = value;
					this.SendPropertyChanged("Parent_CategoriaID");
					this.OnParent_CategoriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_Categorias_Categorias", Storage="_Parent_Categoria", ThisKey="Parent_CategoriaID", OtherKey="CategoriaID", IsForeignKey=true)]
		public Categorias Parent_Categoria
		{
			get
			{
				return this._Parent_Categoria.Entity;
			}
			set
			{
				Categorias previousValue = this._Parent_Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Parent_Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Parent_Categoria.Entity = null;
						previousValue.Categoria.Remove(this);
					}
					this._Parent_Categoria.Entity = value;
					if ((value != null))
					{
						value.Categoria.Add(this);
						this._Parent_CategoriaID = value.CategoriaID;
					}
					else
					{
						this._Parent_CategoriaID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("Parent_Categoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK_Categorias_Categorias", Storage="_Categoria", ThisKey="CategoriaID", OtherKey="Parent_CategoriaID", DeleteRule="NO ACTION")]
		public EntitySet<Categorias> Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				this._Categoria.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Categoria(Categorias entity)
		{
			this.SendPropertyChanging();
			entity.Parent_Categoria = this;
		}
		
		private void detach_Categoria(Categorias entity)
		{
			this.SendPropertyChanging();
			entity.Parent_Categoria = null;
		}
	}
}
#pragma warning restore 1591
